# Generated by Django 5.2.8 on 2025-12-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_template'),
    ]


from django.utils.text import slugify

def seed_templates(apps, schema_editor):
    Template = apps.get_model('resumes', 'Template')
    templates = [
        {
            "id": "classic-1",
            "name": "Classic",
            "description": "Traditional single-column layout, perfect for conservative industries.",
            "category": "professional",
            "preview_image_url": "/static/templates/classic-1.jpg"
        },
        {
            "id": "modern-1",
            "name": "Modern",
            "description": "Clean and contemporary design with a touch of color.",
            "category": "creative",
            "preview_image_url": "/static/templates/modern-1.jpg"
        },
        {
            "id": "executive-1",
            "name": "Executive",
            "description": "Sophisticated layout for senior roles and management.",
            "category": "professional",
            "preview_image_url": "/static/templates/executive-1.jpg"
        },
        {
            "id": "creative-1",
            "name": "Creative",
            "description": "Bold design for designers and artists.",
            "category": "creative",
            "preview_image_url": "/static/templates/creative-1.jpg"
        },
        {
            "id": "minimal-1",
            "name": "Minimal",
            "description": "Simple and effective, focusing on content.",
            "category": "minimal",
            "preview_image_url": "/static/templates/minimal-1.jpg"
        },
    ]
    
    for t in templates:
        Template.objects.create(
            id=t["id"],
            name=t["name"],
            slug=slugify(t["name"]),
            description=t["description"],
            category=t["category"],
            preview_image_url=t["preview_image_url"],
            is_active=True
        )

def reverse_seed(apps, schema_editor):
    Template = apps.get_model('resumes', 'Template')
    Template.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_template'),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_seed),
    ]
