# Generated by Django 5.2.8 on 2025-12-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_seed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='resumes.template'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template_id',
            field=models.CharField(default='classic-1', max_length=20),
        ),
    ]
