# Generated by Django 5.2.8 on 2025-12-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_template_link_alter_resume_template_id'),
    ]


def populate_template_link(apps, schema_editor):
    Resume = apps.get_model('resumes', 'Resume')
    Template = apps.get_model('resumes', 'Template')
    
    # Cache templates to avoid repeated queries
    templates = {t.id: t for t in Template.objects.all()}
    
    for resume in Resume.objects.all():
        if resume.template_id in templates:
            resume.template_link = templates[resume.template_id]
            resume.save()
        else:
            # Fallback for unknown templates, or handle as error?
            # Assuming 'classic-1' as safe default
            if 'classic-1' in templates:
                resume.template_link = templates['classic-1']
                resume.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_template_link_alter_resume_template_id'),
    ]

    operations = [
        migrations.RunPython(populate_template_link),
    ]
