# Generated by Django 5.2.8 on 2025-12-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_populate_template_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='template_link',
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(db_column='template_id', default='classic-1', on_delete=django.db.models.deletion.PROTECT, to='resumes.template', verbose_name='Template'),
        ),
    ]
