# Generated by Django 5.2.8 on 2025-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_remove_resume_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='section_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='definition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
