# Generated by Django'S migration system

from django.db import migrations

def backfill_templates(apps, schema_editor):
    Template = apps.get_model('resumes', 'Template')
    default_definition = {
        "schema_version": 1,
        "layout": {
            "type": "two_column",
            "header": "top",
            "columns": { "left": 0.35, "right": 0.65 }
        },
        "style": {
            "font_family": "Inter",
            "heading_scale": 1.0,
            "body_scale": 1.0,
            "primary_color": "#111827",
            "accent_color": "#2563EB",
            "section_gap": 16,
            "line_height": 1.4
        },
        "sections": {
            "personal_info": { "area": "header", "order": 1, "visible": True },
            "work_experiences": { "area": "left", "order": 2, "visible": True },
            "educations": { "area": "left", "order": 3, "visible": True },
            "skill_categories": { "area": "right", "order": 4, "visible": True, "display": "bars" },
            "strengths": { "area": "right", "order": 5, "visible": True },
            "hobbies": { "area": "right", "order": 6, "visible": True },
            "custom_sections": { "area": "full", "order": 7, "visible": True }
        }
    }
    
    # Update all templates to have this definition if they don't have one
    for template in Template.objects.all():
        if not template.definition:
            template.definition = default_definition
            template.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resume_section_settings_template_definition'),
    ]

    operations = [
        migrations.RunPython(backfill_templates, migrations.RunPython.noop),
    ]
