# Generated by Django 5.2.8 on 2025-12-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='professional', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('preview_image_url', models.CharField(blank=True, max_length=500)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='coverletter',
            name='template',
            field=models.ForeignKey(db_column='template_id', default='standard-1', on_delete=django.db.models.deletion.PROTECT, to='cover_letters.coverlettertemplate'),
        ),
    ]
