# Generated by Django 5.1.4 on 2025-12-19

from django.db import migrations


def create_default_template(apps, schema_editor):
    """Create default cover letter template."""
    CoverLetterTemplate = apps.get_model('cover_letters', 'CoverLetterTemplate')
    
    default_template = CoverLetterTemplate(
        id='standard-1',
        name='Standard Professional',
        slug='standard-professional',
        description='Classic professional cover letter template',
        category='professional',
        is_active=True,
        is_premium=False,
        definition={
            'schema_version': 1,
            'layout': {
                'type': 'single-column',
                'spacing': 'normal',
                'margins': '1in'
            },
            'style': {
                'font_family': 'Arial, sans-serif',
                'font_size': '11pt',
                'color': '#333333'
            },
            'sections': {
                'header': {
                    'visible': True,
                    'order': 0
                },
                'body': {
                    'visible': True,
                    'order': 1
                },
                'signature': {
                    'visible': True,
                    'order': 2
                }
            }
        }
    )
    default_template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letters', '0002_coverlettertemplate_coverletter_template'),
    ]

    operations = [
        migrations.RunPython(create_default_template, reverse_code=migrations.RunPython.noop),
    ]
