# Generated by Django 5.2.8 on 2025-12-19 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('summary', 'Summary Generation'), ('bullets', 'Bullet Point Optimization'), ('experience', 'Experience Description'), ('rewrite', 'Text Rewrite'), ('cover_letter_base', 'Cover Letter Base'), ('cover_letter_full', 'Full Cover Letter'), ('resume_preview', 'Resume Preview'), ('other', 'Other')], default='other', max_length=50)),
                ('prompt_hash', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(max_length=50)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ai_core_aiu_created_49df68_idx'), models.Index(fields=['user', 'feature_type'], name='ai_core_aiu_user_id_ba22c8_idx')],
            },
        ),
    ]
